In [1]:
from lxml import html
import requests
from collections import OrderedDict
import json
import argparse
import pandas as pd
import csv

def parse(input_file):
    restaurants = []
    for line in input_file:
        url = line
        response = requests.get(url).text
        parser = html.fromstring(response)
	
        XPATH_RATING = '//div[@id="ratingFilter"]//ul//li'

        XPATH_TRAVELER = '//div[@class="col segment extraWidth"]//ul//li'
        XPATH_TIME = '//div[@class="col season extraWidth"]//ul/li'
        XPATH_LANGUAGE = '//div[@class="col language extraWidth"]//ul/li'
#        XPATH_DETAILS = '//div[contains(@class,"details_tab")]//div[contains(@class, "table_section")]//text()'
        XPATH_NAME = '//h1[@property="name"]//text()'
        XPATH_HOTEL_RATING = '//span[@property="ratingValue"]//@content'
        XPATH_REVIEWS = '//a[@property="reviewCount"]/@content'
        XPATH_RANK = '//div[@class="slim_ranking"]//text()'
#         XPATH_OFFICIAL_DESCRIPTION = '//div[contains(@class,"additional_info")]//span[contains(@class,"tabs_descriptive_text")]//text()'
#         XPATH_OFFICIAL_DESCRIPTION = '//div[@class="additional_info"]//div'
        XPATH_LATITUDE = '//div[@class="mapContainer"]//@data-lat'
        XPATH_LONGITUDE = '//div[@class="mapContainer"]//@data-lng'
                                        
        ratings = parser.xpath(XPATH_RATING)
        travelers = parser.xpath(XPATH_TRAVELER)
        times = parser.xpath(XPATH_TIME)
        languages = parser.xpath(XPATH_LANGUAGE)
	
        raw_name = parser.xpath(XPATH_NAME)
        raw_rank = parser.xpath(XPATH_RANK)
        raw_review_count = parser.xpath(XPATH_REVIEWS)
        raw_rating = parser.xpath(XPATH_HOTEL_RATING)
#         raw_official_description = parser.xpath(XPATH_OFFICIAL_DESCRIPTION)
#        raw_details = parser.xpath(XPATH_DETAILS)
        raw_latitude = parser.xpath(XPATH_LATITUDE)
        raw_longitude = parser.xpath(XPATH_LONGITUDE)
					
        name = ''.join(raw_name).strip() if raw_name else None
        rank = ''.join(raw_rank).strip() if raw_rank else None
        review_count = ''.join(raw_review_count).strip() if raw_review_count else None
        hotel_rating = ''.join(raw_rating).strip() if raw_rating else None
#         official_description = ' '.join(' '.join(raw_official_description).split()) if raw_official_description else None
#        details = ' '.join(' '.join(raw_details).split()) if raw_details else None
        latitude = ' '.join(' '.join(raw_latitude).split()) if raw_latitude else None  
        longitude = ' '.join(' '.join(raw_longitude).split()) if raw_longitude else None 

        ratings_dict = OrderedDict()
        for rating in ratings:
            XPATH_RATING_KEY = './/div[@class="row_label"]//text()'
            XPATH_RATING_VALUE = './/span[@class="row_bar"]/following-sibling::span//text()'
            raw_rating_key = rating.xpath(XPATH_RATING_KEY)
            raw_rating_value = rating.xpath(XPATH_RATING_VALUE)
            cleaned_rating_key = ''.join(raw_rating_key).replace('\n','')
            cleaned_rating_value = ''.join(raw_rating_value).replace('\n','')
            ratings_dict.update({cleaned_rating_key:cleaned_rating_value})
    
        travelers_list = [] 
        for traveler in travelers:
            XPATH_TRAVELER_TYPE = './/label//text()'
            XPATH_TRAVELER_COUNT = './/span//text()'
            raw_traveler_type = traveler.xpath(XPATH_TRAVELER_TYPE)
            raw_traveler_count = traveler.xpath(XPATH_TRAVELER_COUNT)
            cleaned_traveler_type = ''.join(raw_traveler_type).replace('\n','').split(' ')
            cleaned_traveler_type = cleaned_traveler_type[0]
            cleaned_traveler_count = ''.join(raw_traveler_count).replace('\n','')
            travelers_list.append((cleaned_traveler_type,cleaned_traveler_count))
        
        times_list = []
        for time in times:
            XPATH_TIME_TYPE = './/label//text()'
            XPATH_TIME_COUNT = './/span//text()'
            raw_time_type = time.xpath(XPATH_TIME_TYPE)
            raw_time_count = time.xpath(XPATH_TIME_COUNT)
            cleaned_time_type = ''.join(raw_time_type).replace('\n','').split(' ')
            cleaned_time_type = cleaned_time_type[0]
            cleaned_time_count = ''.join(raw_time_count).replace('\n','')
            times_list.append((cleaned_time_type, cleaned_time_count))
        
        language_list = []
        for language in languages:
            XPATH_LANGUAGE_TYPE = './/label//text()'
            XPATH_LANGUAGE_COUNT = './/span//text()'
            raw_language_type = language.xpath(XPATH_LANGUAGE_TYPE)
            raw_language_count = language.xpath(XPATH_LANGUAGE_COUNT)
            cleaned_language_type = ''.join(raw_language_type).replace('\n','').split(' ')
            cleaned_language_type = cleaned_language_type[0]
            cleaned_language_count = ''.join(raw_language_count).replace('\n','')
            language_list.append(cleaned_language_type)
        language_list = language_list[1:]


        data = {'name':name,
				'rank':rank,
				'rating':hotel_rating,
                'review_count':review_count,
                'latitude':latitude,
                'longitude':longitude,
#                 'official_description':official_description,
                  'travelers':travelers_list,
                  'times of year':times_list,
                  'languages':language_list
#                  'details':details
	    }
        restaurants.append(data)
        
        
#    columns = ['property_title', 'rank', 'rating', 'review_count', 'location', 'official_description', 'travelers', 'times', 'langauges']
    df = pd.DataFrame(restaurants)
    return df



input_file = open('links.csv', 'r')
links = []
for i in input_file:
    links.append('https://www.tripadvisor.com'+i)
scraped_data = parse(links)
scraped_data

,languages,latitude,longitude,name,rank,rating,review_count,times of year,travelers
0,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56..."
1,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18..."
2,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4..."
3,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1..."
4,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2..."
5,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9..."
6,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)..."
7,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),..."
8,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (..."
9,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)..."
10,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1..."
11,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22..."
12,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15..."
13,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33..."
14,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)..."
15,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)..."
16,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)..."
17,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)..."
18,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)..."
19,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),..."
20,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15..."
21,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25..."
22,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)..."
23,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11..."
24,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)..."
25,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))..."
26,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),..."
27,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))..."
28,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)..."
29,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18..."
...,...,...,...,...,...,...,...,...,...
540,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56..."
541,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18..."
542,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4..."
543,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1..."
544,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2..."
545,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9..."
546,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)..."
547,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),..."
548,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (..."
549,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)..."
550,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1..."
551,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22..."
552,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15..."
553,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33..."
554,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)..."
555,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)..."
556,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)..."
557,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)..."
558,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)..."
559,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),..."
560,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15..."
561,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25..."
562,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)..."
563,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11..."
564,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)..."
565,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))..."
566,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),..."
567,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))..."
568,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)..."
569,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18..."

In [2]:
with open('restaurants_details4.csv', 'w') as csvfile:
    scraped_data.to_csv(csvfile,columns = ['latitude','longitude','name'], encoding='utf-8')

In [3]:
scraped_data.dropna()

,languages,latitude,longitude,name,rank,rating,review_count,times of year,travelers
0,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56..."
1,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18..."
2,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4..."
3,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1..."
4,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2..."
5,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9..."
6,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)..."
7,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),..."
8,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (..."
9,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)..."
10,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1..."
11,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22..."
12,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15..."
13,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33..."
14,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)..."
15,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)..."
16,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)..."
17,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)..."
18,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)..."
19,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),..."
20,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15..."
21,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25..."
22,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)..."
23,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11..."
24,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)..."
25,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))..."
26,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),..."
27,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))..."
28,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)..."
29,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18..."
...,...,...,...,...,...,...,...,...,...
540,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56..."
541,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18..."
542,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4..."
543,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1..."
544,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2..."
545,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9..."
546,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)..."
547,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),..."
548,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (..."
549,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)..."
550,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1..."
551,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22..."
552,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15..."
553,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33..."
554,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)..."
555,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)..."
556,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)..."
557,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)..."
558,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)..."
559,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),..."
560,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15..."
561,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25..."
562,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)..."
563,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11..."
564,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)..."
565,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))..."
566,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),..."
567,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))..."
568,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)..."
569,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18..."

In [4]:
scraped_data2 = pd.DataFrame(scraped_data.dropna())

In [5]:
lat = [(float(x)) for x in scraped_data2['latitude']]
long = [(float(x)) for x in scraped_data2['longitude']]

In [6]:
#print((max(lat)+min(lat))/2)
print((max(lat)))
print((min(lat)))
print((max(long)+min(long))/2)

31.992243
31.845284
35.905562

In [7]:
#import gmplot

#gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)

#gmap.plot(latitudes, longitudes, 'cornflowerblue', edge_width=10)
#gmap.scatter(more_lats, more_lngs, '#3B0B39', size=40, marker=False)
#gmap.scatter(marker_lats, marker_lngs, 'k', marker=True)
#gmap.heatmap(heat_lats, heat_lngs)

#gmap.draw("mymap.html")

In [8]:
import gmplot
# __, __ center map , __ zoom of map
gmap = gmplot.GoogleMapPlotter(31.918763499999997, 35.905562, 10)
gmap.scatter(lat[0:35], long[0:35],'#3B0B39', size=20, marker=False)
#gmap.heatmap(lat,long)
gmap.draw("Amman_map4.html")

In [9]:
gmap = gmplot.GoogleMapPlotter(31.950000, 35.920000, 12)
gmap.heatmap(lat,long)
gmap.draw("Amman_heatmap4.html")

In [68]:
import matplotlib
gmap = gmplot.GoogleMapPlotter(31.950000, 35.920000, 12)
#Labels = list(set(scraped_data2[3]))
#colors = list(matplotlib.colors.cnames)[::2]
for j in scraped_data2:
    gmap.scatter(lat, long,'#3B0B39',label=str(j), marker=False)
gmap.draw("map.html")

In [ ]:
def plottingCluster(points, labels, gm=False, gm_name='cluster.html'):
    Labels = list(set(labels))
    colors = list(matplotlib.colors.cnames)[::2]
    X = dict()
    for b in range(len(labels)):
        if labels[b] in X:
            X[labels[b]][0].append(points[b][0])
            X[labels[b]][1].append(points[b][1])
        else:
            X[labels[b]] = [[], []]
            X[labels[b]][0].append(points[b][0])
            X[labels[b]][1].append(points[b][1])
    plt.figure(figsize=(20, 10))
    if gm:
        gmap = gmplot.GoogleMapPlotter(points[0][0], points[0][1], 11)
        for j in X:
            gmap.scatter(X[j][0], X[j][1], colors[Labels.index(j)], marker=True)
        gmap.draw(gm_name)
    for l in X:
        plt.scatter(X[l][0], X[l][1], color=colors[Labels.index(l)], label=str(l), marker=".")
    plt.legend()

In [ ]:
for l in X:
    plt.scatter(X[l][0], X[l][1], color=colors[Labels.index(l)], label=str(l), marker=".")
plt.legend()

In [10]:
#https://pypi.python.org/pypi/gmplot/1.0.5

In [11]:
#https://github.com/tcassou/gmaps    map examples

In [12]:
from collections import Counter
import re
#def convert(string):
#    return Counter(re.findall('[A-Z][a-z]*', string))
import ast
languages_dictsList = []
for i in scraped_data2['languages']:
    lang = (re.findall('[A-Z][a-z]*', str(i)))
    freq = (re.findall('[1-9][0-9]*', str(i)))
    dictionary = dict(zip(lang, freq))
    languages_dictsList.append(dictionary)
lang_df = pd.DataFrame(languages_dictsList)
new_names = [(i,'lang_'+i) for i in lang_df.iloc[:, 0:].columns.values]
lang_df.rename(columns = dict(new_names), inplace=True) #adding prefix to know what type of cat
resulting_df = scraped_data2.join(lang_df)
resulting_df.fillna(value=0, inplace=True) #final dataframe with languages of reviews as categories

In [13]:
travelers_dictsList = []
for i in scraped_data2['travelers']:
    trav = (re.findall('[A-Z][a-z]*', str(i)))
    freq = (re.findall('[1-9][0-9]*', str(i)))
    dictionary = dict(zip(trav, freq))
    travelers_dictsList.append(dictionary)
travelers_df = pd.DataFrame(travelers_dictsList)
new_names = [(i,'travType_'+i) for i in travelers_df.iloc[:, 0:].columns.values] 
travelers_df.rename(columns = dict(new_names), inplace=True) #adding prefix to know what type of cat
resulting_df2 = resulting_df.join(travelers_df)
resulting_df2.fillna(value=0, inplace=True) #types of travelers added as categories

In [14]:
import sklearn
import sklearn.cluster
import numpy as np
matrix = resulting_df2[['latitude','longitude']].as_matrix()
np.nan_to_num(matrix)
km = sklearn.cluster.KMeans(n_clusters=4)
km.fit(matrix)
# Get cluster assignment labels
labels = km.labels_
# Format results as a DataFrame
results = pd.DataFrame([resulting_df2.index,labels]).T

In [15]:
print(labels)

[3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1
 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3
 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3
 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1
 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3
 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3
 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1
 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1
 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3
 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1
 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2
 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0
 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3
 1 3 3 3 0 1 0 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0
 3 1 0 3 3 3 1 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3 3 1 3 3 3 0 1 0 3 1 0 3 3 3 1
 1 2 1 1 3 3 3 0 0 1 1 1 1 1 3]

In [16]:
resulting_df2

,languages,latitude,longitude,name,rank,rating,review_count,times of year,travelers,lang_Arabic,...,lang_German,lang_Italian,lang_Japanese,lang_Russian,lang_Spanish,travType_Business,travType_Couples,travType_Families,travType_Friends,travType_Solo
0,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56...",0,...,0,0,0,0,20,8,58,24,69,56
1,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18...",4,...,0,0,0,0,0,8,24,56,133,18
2,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4...",40,...,0,0,0,0,0,31,74,150,144,49
3,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1...",28,...,0,31,0,0,0,113,79,165,166,12
4,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2...",0,...,0,33,0,0,0,81,88,126,198,23
5,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9...",0,...,0,79,0,0,56,61,77,111,133,9
6,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)...",0,...,0,3,0,0,0,22,26,21,172,9
7,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),...",0,...,0,0,1,0,0,18,7,9,19,3
8,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (...",0,...,0,44,0,0,0,32,219,167,333,126
9,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)...",0,...,0,2,0,0,0,9,14,21,31,2
10,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1...",25,...,0,8,0,0,0,13,25,142,81,16
11,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22...",0,...,0,7,0,0,0,9,33,30,46,22
12,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15...",0,...,4,3,0,0,0,19,37,28,97,15
13,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33...",0,...,0,15,0,0,11,30,77,37,103,33
14,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)...",0,...,2,0,0,0,4,6,20,29,45,1
15,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)...",7,...,0,0,0,0,0,32,17,32,32,8
16,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)...",10,...,0,5,0,0,0,28,14,39,0,12
17,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)...",0,...,0,8,0,0,0,61,24,55,72,8
18,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)...",3,...,0,0,0,0,0,18,13,18,26,1
19,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),...",0,...,2,0,0,0,2,3,4,9,27,4
20,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15...",0,...,0,0,0,0,0,3,12,24,48,15
21,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25...",0,...,0,13,0,0,0,13,45,27,125,25
22,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)...",2,...,0,3,0,0,0,36,18,12,31,1
23,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11...",21,...,0,18,0,0,0,46,30,60,49,11
24,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)...",0,...,0,0,0,2,0,16,16,20,53,3
25,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))...",0,...,0,0,0,0,1,7,12,9,6,2
26,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),...",5,...,0,0,0,0,0,0,2,7,0,6
27,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))...",0,...,0,5,0,0,0,8,16,8,17,2
28,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)...",0,...,0,5,0,0,0,12,23,22,52,5
29,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18...",8,...,0,0,0,0,9,5,21,27,39,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,"[English(233), Spanish(20), French(16), ]",31.952438,35.937958,Pizza Roma Cafe,#1 of 550 Restaurants in Amman,4.5,305,"[(Mar-May, (67)), (Jun-Aug, (39)), (Sep-Nov, (...","[(Families, (24)), (Couples, (58)), (Solo, (56...",0,...,0,0,0,0,20,8,58,24,69,56
541,"[English(261), Arabic(4), French(2), ]",31.963032,35.89816,Brisket,#2 of 550 Restaurants in Amman,4.5,270,"[(Mar-May, (56)), (Jun-Aug, (58)), (Sep-Nov, (...","[(Families, (56)), (Couples, (24)), (Solo, (18...",4,...,0,0,0,0,0,8,24,56,133,18
542,"[English(538), Arabic(40), Chinese, ]",31.951878,35.9332,Habibah Sweets,#3 of 550 Restaurants in Amman,4.5,674,"[(Mar-May, (158)), (Jun-Aug, (119)), (Sep-Nov,...","[(Families, (150)), (Couples, (74)), (Solo, (4...",40,...,0,0,0,0,0,31,74,150,144,49
543,"[English(677), Italian(31), Arabic(28), ]",31.952278,35.92017,Fakhreldin Restaurant,#4 of 550 Restaurants in Amman,4.5,790,"[(Mar-May, (203)), (Jun-Aug, (146)), (Sep-Nov,...","[(Families, (165)), (Couples, (79)), (Solo, (1...",28,...,0,31,0,0,0,113,79,165,166,12
544,"[English(606), Italian(33), Chinese, ]",31.94924,35.929058,Sufra Restaurant,#5 of 550 Restaurants in Amman,4.5,705,"[(Mar-May, (181)), (Jun-Aug, (134)), (Sep-Nov,...","[(Families, (126)), (Couples, (88)), (Solo, (2...",0,...,0,33,0,0,0,81,88,126,198,23
545,"[English(460), Italian(79), Spanish(56), ]",31.992243,35.866783,Tawaheen al-Hawa,#6 of 550 Restaurants in Amman,4.5,713,"[(Mar-May, (133)), (Jun-Aug, (89)), (Sep-Nov, ...","[(Families, (111)), (Couples, (77)), (Solo, (9...",0,...,0,79,0,0,56,61,77,111,133,9
546,"[English(273), French(4), Italian(3), ]",31.952156,35.91342,Chestnut Restaurant & Pub,#8 of 550 Restaurants in Amman,4.5,284,"[(Mar-May, (80)), (Jun-Aug, (57)), (Sep-Nov, (...","[(Families, (21)), (Couples, (26)), (Solo, (9)...",0,...,0,3,0,0,0,22,26,21,172,9
547,"[English(59), Japanese(1)]",31.961784,35.8701,V Lounge & Restaurant,#7 of 550 Restaurants in Amman,5,60,"[(Mar-May, (55)), (Jun-Aug, (2)), (Sep-Nov, (1...","[(Families, (9)), (Couples, (7)), (Solo, (3)),...",0,...,0,0,1,0,0,18,7,9,19,3
548,"[English(1,044), Italian(109), French(46), ]",31.952234,35.93188,Hashem,#9 of 550 Restaurants in Amman,4.5,1373,"[(Mar-May, (296)), (Jun-Aug, (226)), (Sep-Nov,...","[(Families, (167)), (Couples, (219)), (Solo, (...",0,...,0,44,0,0,0,32,219,167,333,126
549,"[English(81), French(2), Italian(2), ]",31.953451,35.884483,Melograno,#11 of 550 Restaurants in Amman,4.5,86,"[(Mar-May, (29)), (Jun-Aug, (7)), (Sep-Nov, (2...","[(Families, (21)), (Couples, (14)), (Solo, (2)...",0,...,0,2,0,0,0,9,14,21,31,2
550,"[English(307), Arabic(25), Italian(8), ]",31.987595,35.866623,Abu Jbara,#10 of 550 Restaurants in Amman,4.5,351,"[(Mar-May, (69)), (Jun-Aug, (79)), (Sep-Nov, (...","[(Families, (142)), (Couples, (25)), (Solo, (1...",25,...,0,8,0,0,0,13,25,142,81,16
551,"[English(170), Italian(7), French(5), ]",31.94937,35.92642,Al-Quds,#12 of 550 Restaurants in Amman,4.5,197,"[(Mar-May, (47)), (Jun-Aug, (38)), (Sep-Nov, (...","[(Families, (30)), (Couples, (33)), (Solo, (22...",0,...,0,7,0,0,0,9,33,30,46,22
552,"[English(223), German(4), Italian(3), ]",31.956652,35.94576,Beit Sitti,#14 of 550 Restaurants in Amman,4.5,238,"[(Mar-May, (56)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (28)), (Couples, (37)), (Solo, (15...",0,...,4,3,0,0,0,19,37,28,97,15
553,"[English(364), Italian(15), Spanish(11), ]",31.951536,35.93099,Wild Jordan Center,#13 of 550 Restaurants in Amman,4,418,"[(Mar-May, (121)), (Jun-Aug, (68)), (Sep-Nov, ...","[(Families, (37)), (Couples, (77)), (Solo, (33...",0,...,0,15,0,0,11,30,77,37,103,33
554,"[English(109), Spanish(4), German(2), ]",31.952919,35.903458,Lucca Steakhouse,#15 of 550 Restaurants in Amman,4.5,117,"[(Mar-May, (34)), (Jun-Aug, (19)), (Sep-Nov, (...","[(Families, (29)), (Couples, (20)), (Solo, (1)...",0,...,2,0,0,0,4,6,20,29,45,1
555,"[English(146), Arabic(7), French(4), ]",31.953556,35.914356,Burj Al Hamam,#16 of 550 Restaurants in Amman,4.5,160,"[(Mar-May, (26)), (Jun-Aug, (43)), (Sep-Nov, (...","[(Families, (32)), (Couples, (17)), (Solo, (8)...",7,...,0,0,0,0,0,32,17,32,32,8
556,"[English(113), Arabic(10), Italian(5), ]",31.845284,35.91387,Kan Zamaan,#17 of 550 Restaurants in Amman,4.5,142,"[(Mar-May, (31)), (Jun-Aug, (26)), (Sep-Nov, (...","[(Families, (39)), (Couples, (14)), (Solo, (0)...",10,...,0,5,0,0,0,28,14,39,0,12
557,"[English(251), Italian(8), French(4), ]",31.952505,35.907158,Levant,#18 of 550 Restaurants in Amman,4.5,275,"[(Mar-May, (74)), (Jun-Aug, (59)), (Sep-Nov, (...","[(Families, (55)), (Couples, (24)), (Solo, (8)...",0,...,0,8,0,0,0,61,24,55,72,8
558,"[English(84), French(7), Arabic(3), ]",31.941225,35.888035,Levant Restaurant,#19 of 550 Restaurants in Amman,4.5,100,"[(Mar-May, (21)), (Jun-Aug, (23)), (Sep-Nov, (...","[(Families, (18)), (Couples, (13)), (Solo, (1)...",3,...,0,0,0,0,0,18,13,18,26,1
559,"[English(52), German(2), Spanish(2), ]",31.95136,35.916283,Rosa Damascena,#20 of 550 Restaurants in Amman,4.5,57,"[(Mar-May, (21)), (Jun-Aug, (9)), (Sep-Nov, (8...","[(Families, (9)), (Couples, (4)), (Solo, (4)),...",0,...,2,0,0,0,2,3,4,9,27,4
560,"[English(111), Chinese, Arabic(6), ]",31.952257,35.93196,Hashim Restaurant,#21 of 550 Restaurants in Amman,4.5,132,"[(Mar-May, (38)), (Jun-Aug, (16)), (Sep-Nov, (...","[(Families, (24)), (Couples, (12)), (Solo, (15...",0,...,0,0,0,0,0,3,12,24,48,15
561,"[English(297), Italian(13), French(12), ]",31.948015,35.931316,Books at Cafe,#22 of 550 Restaurants in Amman,4,344,"[(Mar-May, (75)), (Jun-Aug, (71)), (Sep-Nov, (...","[(Families, (27)), (Couples, (45)), (Solo, (25...",0,...,0,13,0,0,0,13,45,27,125,25
562,"[English(146), Italian(3), Arabic(2), ]",31.96674,35.87306,Tannoureen,#23 of 550 Restaurants in Amman,4.5,158,"[(Mar-May, (39)), (Jun-Aug, (34)), (Sep-Nov, (...","[(Families, (12)), (Couples, (18)), (Solo, (1)...",2,...,0,3,0,0,0,36,18,12,31,1
563,"[English(240), Arabic(21), Italian(18), ]",31.991304,35.865364,Reem albawadi,#24 of 550 Restaurants in Amman,4,310,"[(Mar-May, (85)), (Jun-Aug, (60)), (Sep-Nov, (...","[(Families, (60)), (Couples, (30)), (Solo, (11...",21,...,0,18,0,0,0,46,30,60,49,11
564,"[English(135), French(4), Russian(2), ]",31.952566,35.9041,Yoshi,#26 of 550 Restaurants in Amman,4,144,"[(Mar-May, (29)), (Jun-Aug, (36)), (Sep-Nov, (...","[(Families, (20)), (Couples, (16)), (Solo, (3)...",0,...,0,0,0,2,0,16,16,20,53,3
565,"[English(36), French(2), Spanish(1)]",31.965462,35.901966,Gusto,#25 of 550 Restaurants in Amman,4.5,39,"[(Mar-May, (18)), (Jun-Aug, (0)), (Sep-Nov, (4...","[(Families, (9)), (Couples, (12)), (Solo, (2))...",0,...,0,0,0,0,1,7,12,9,6,2
566,"[English(15), Arabic(5)]",31.946836,35.878162,Clemance Restaurant,#27 of 550 Restaurants in Amman,5,20,"[(Mar-May, (15)), (Jun-Aug, (0)), (Sep-Nov, (0...","[(Families, (7)), (Couples, (2)), (Solo, (0)),...",5,...,0,0,0,0,0,0,2,7,0,6
567,"[English(54), Italian(5), French(1), ]",31.973347,35.90616,IL Terrazzo Amman Restaurant,#31 of 550 Restaurants in Amman,4.5,61,"[(Mar-May, (17)), (Jun-Aug, (12)), (Sep-Nov, (...","[(Families, (8)), (Couples, (16)), (Solo, (2))...",0,...,0,5,0,0,0,8,16,8,17,2
568,"[English(123), Italian(5), French(3), ]",31.973473,35.89811,Vinaigrette,#30 of 550 Restaurants in Amman,4,139,"[(Mar-May, (37)), (Jun-Aug, (27)), (Sep-Nov, (...","[(Families, (22)), (Couples, (23)), (Solo, (5)...",0,...,0,5,0,0,0,12,23,22,52,5
569,"[English(126), Spanish(9), Arabic(8), ]",31.952627,35.93221,Al-Quds Restaurant,#29 of 550 Restaurants in Amman,4,166,"[(Mar-May, (38)), (Jun-Aug, (28)), (Sep-Nov, (...","[(Families, (27)), (Couples, (21)), (Solo, (18...",8,...,0,0,0,0,9,5,21,27,39,18

In [17]:
#resulting_df2.hist('name', columns=['travType_Business','travType_Couples','travType_Families','travType_Friends','travType_Solo'])

In [18]:
print(resulting_df2.columns)

Index(['languages', 'latitude', 'longitude', 'name', 'rank', 'rating',
       'review_count', 'times of year', 'travelers', 'lang_Arabic',
       'lang_Chinese', 'lang_English', 'lang_French', 'lang_German',
       'lang_Italian', 'lang_Japanese', 'lang_Russian', 'lang_Spanish',
       'travType_Business', 'travType_Couples', 'travType_Families',
       'travType_Friends', 'travType_Solo'],
      dtype='object')

In [19]:
print(type(resulting_df2['lang_English']))

<class 'pandas.core.series.Series'>

In [20]:
df2 = resulting_df2.groupby(['lang_Arabic','lang_Chinese','lang_English','lang_French', 'lang_German',
       'lang_Italian', 'lang_Japanese', 'lang_Russian', 'lang_Spanish'])

In [24]:
df2 = resulting_df2.groupby((i for i in ['lang_Arabic'])).mean()

TypeError: 'generator' object is not callable

In [25]:
df2 = resulting_df2.groupby(['lang_English'])['review_count'].sum()
df2
df2.plot(kind="bar")

TypeError: Empty 'DataFrame': no numeric data to plot

In [26]:
trav_typedf = resulting_df2[['travType_Business','travType_Couples','travType_Families','travType_Friends','travType_Solo']]

In [41]:
from sklearn.feature_extraction import DictVectorizer

In [40]:
trav_typedf.T.to_dict().values()

dict_values([{'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Business': '113', 'travType_Families': '165', 'travType_Solo': '12'}, {'travType_Friends': '198', 'travType_Couples': '88', 'travType_Business': '81', 'travType_Families': '126', 'travType_Solo': '23'}, {'travType_Friends': '133', 'travType_Couples': '77', 'travType_Business': '61', 'travType_Families': '111', 'travType_Solo': '9'}, {'travType_Friends': '172', 'travType_Couples': '26', 'travType_Business': '22', 'travType_Families': '21', 'travType_Solo': '9'}, {'travType_Friends': '19', 'travType_Couples': '7', 'travType_Business': '18', 'travType_Families': '9', 'travType_Solo': '3'}, {'travType_Friends': '333', 'travType_Couples': '219', 'travType_Business': '32', 'travType_Families': '167', 'travType_Solo': '126'}, {'travType_Friends': '31', 'travType_Couples': '14', 'travType_Business': '9', 'travType_Families': '21', 'travType_Solo': '2'}, {'travType_Friends': '81', 'travType_Couples': '25', 'travType_Business': '13', 'travType_Families': '142', 'travType_Solo': '16'}, {'travType_Friends': '46', 'travType_Couples': '33', 'travType_Business': '9', 'travType_Families': '30', 'travType_Solo': '22'}, {'travType_Friends': '97', 'travType_Couples': '37', 'travType_Business': '19', 'travType_Families': '28', 'travType_Solo': '15'}, {'travType_Friends': '103', 'travType_Couples': '77', 'travType_Business': '30', 'travType_Families': '37', 'travType_Solo': '33'}, {'travType_Friends': '45', 'travType_Couples': '20', 'travType_Business': '6', 'travType_Families': '29', 'travType_Solo': '1'}, {'travType_Friends': '32', 'travType_Couples': '17', 'travType_Business': '32', 'travType_Families': '32', 'travType_Solo': '8'}, {'travType_Friends': 0, 'travType_Couples': '14', 'travType_Business': '28', 'travType_Families': '39', 'travType_Solo': '12'}, {'travType_Friends': '72', 'travType_Couples': '24', 'travType_Business': '61', 'travType_Families': '55', 'travType_Solo': '8'}, {'travType_Friends': '26', 'travType_Couples': '13', 'travType_Business': '18', 'travType_Families': '18', 'travType_Solo': '1'}, {'travType_Friends': '27', 'travType_Couples': '4', 'travType_Business': '3', 'travType_Families': '9', 'travType_Solo': '4'}, {'travType_Friends': '48', 'travType_Couples': '12', 'travType_Business': '3', 'travType_Families': '24', 'travType_Solo': '15'}, {'travType_Friends': '125', 'travType_Couples': '45', 'travType_Business': '13', 'travType_Families': '27', 'travType_Solo': '25'}, {'travType_Friends': '31', 'travType_Couples': '18', 'travType_Business': '36', 'travType_Families': '12', 'travType_Solo': '1'}, {'travType_Friends': '49', 'travType_Couples': '30', 'travType_Business': '46', 'travType_Families': '60', 'travType_Solo': '11'}, {'travType_Friends': '53', 'travType_Couples': '16', 'travType_Business': '16', 'travType_Families': '20', 'travType_Solo': '3'}, {'travType_Friends': '6', 'travType_Couples': '12', 'travType_Business': '7', 'travType_Families': '9', 'travType_Solo': '2'}, {'travType_Friends': 0, 'travType_Couples': '2', 'travType_Business': 0, 'travType_Families': '7', 'travType_Solo': '6'}, {'travType_Friends': '17', 'travType_Couples': '16', 'travType_Business': '8', 'travType_Families': '8', 'travType_Solo': '2'}, {'travType_Friends': '52', 'travType_Couples': '23', 'travType_Business': '12', 'travType_Families': '22', 'travType_Solo': '5'}, {'travType_Friends': '39', 'travType_Couples': '21', 'travType_Business': '5', 'travType_Families': '27', 'travType_Solo': '18'}, {'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Business': '113', 'travType_Families': '165', 'travType_Solo': '12'}, {'travType_Friends': '198', 'travType_Couples': '88', 'travType_Business': '81', 'travType_Families': '126', 'travType_Solo': '23'}, {'travType_Friends': '133', 'travType_Couples': '77', 'travType_Business': '61', 'travType_Families': '111', 'travType_Solo': '9'}, {'travType_Friends': '172', 'travType_Couples': '26', 'travType_Business': '22', 'travType_Families': '21', 'travType_Solo': '9'}, {'travType_Friends': '19', 'travType_Couples': '7', 'travType_Business': '18', 'travType_Families': '9', 'travType_Solo': '3'}, {'travType_Friends': '333', 'travType_Couples': '219', 'travType_Business': '32', 'travType_Families': '167', 'travType_Solo': '126'}, {'travType_Friends': '31', 'travType_Couples': '14', 'travType_Business': '9', 'travType_Families': '21', 'travType_Solo': '2'}, {'travType_Friends': '81', 'travType_Couples': '25', 'travType_Business': '13', 'travType_Families': '142', 'travType_Solo': '16'}, {'travType_Friends': '46', 'travType_Couples': '33', 'travType_Business': '9', 'travType_Families': '30', 'travType_Solo': '22'}, {'travType_Friends': '97', 'travType_Couples': '37', 'travType_Business': '19', 'travType_Families': '28', 'travType_Solo': '15'}, {'travType_Friends': '103', 'travType_Couples': '77', 'travType_Business': '30', 'travType_Families': '37', 'travType_Solo': '33'}, {'travType_Friends': '45', 'travType_Couples': '20', 'travType_Business': '6', 'travType_Families': '29', 'travType_Solo': '1'}, {'travType_Friends': '32', 'travType_Couples': '17', 'travType_Business': '32', 'travType_Families': '32', 'travType_Solo': '8'}, {'travType_Friends': 0, 'travType_Couples': '14', 'travType_Business': '28', 'travType_Families': '39', 'travType_Solo': '12'}, {'travType_Friends': '72', 'travType_Couples': '24', 'travType_Business': '61', 'travType_Families': '55', 'travType_Solo': '8'}, {'travType_Friends': '26', 'travType_Couples': '13', 'travType_Business': '18', 'travType_Families': '18', 'travType_Solo': '1'}, {'travType_Friends': '27', 'travType_Couples': '4', 'travType_Business': '3', 'travType_Families': '9', 'travType_Solo': '4'}, {'travType_Friends': '48', 'travType_Couples': '12', 'travType_Business': '3', 'travType_Families': '24', 'travType_Solo': '15'}, {'travType_Friends': '125', 'travType_Couples': '45', 'travType_Business': '13', 'travType_Families': '27', 'travType_Solo': '25'}, {'travType_Friends': '31', 'travType_Couples': '18', 'travType_Business': '36', 'travType_Families': '12', 'travType_Solo': '1'}, {'travType_Friends': '49', 'travType_Couples': '30', 'travType_Business': '46', 'travType_Families': '60', 'travType_Solo': '11'}, {'travType_Friends': '53', 'travType_Couples': '16', 'travType_Business': '16', 'travType_Families': '20', 'travType_Solo': '3'}, {'travType_Friends': '6', 'travType_Couples': '12', 'travType_Business': '7', 'travType_Families': '9', 'travType_Solo': '2'}, {'travType_Friends': 0, 'travType_Couples': '2', 'travType_Business': 0, 'travType_Families': '7', 'travType_Solo': '6'}, {'travType_Friends': '17', 'travType_Couples': '16', 'travType_Business': '8', 'travType_Families': '8', 'travType_Solo': '2'}, {'travType_Friends': '52', 'travType_Couples': '23', 'travType_Business': '12', 'travType_Families': '22', 'travType_Solo': '5'}, {'travType_Friends': '39', 'travType_Couples': '21', 'travType_Business': '5', 'travType_Families': '27', 'travType_Solo': '18'}, {'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Business': '113', 'travType_Families': '165', 'travType_Solo': '12'}, {'travType_Friends': '198', 'travType_Couples': '88', 'travType_Business': '81', 'travType_Families': '126', 'travType_Solo': '23'}, {'travType_Friends': '133', 'travType_Couples': '77', 'travType_Business': '61', 'travType_Families': '111', 'travType_Solo': '9'}, {'travType_Friends': '172', 'travType_Couples': '26', 'travType_Business': '22', 'travType_Families': '21', 'travType_Solo': '9'}, {'travType_Friends': '19', 'travType_Couples': '7', 'travType_Business': '18', 'travType_Families': '9', 'travType_Solo': '3'}, {'travType_Friends': '333', 'travType_Couples': '219', 'travType_Business': '32', 'travType_Families': '167', 'travType_Solo': '126'}, {'travType_Friends': '31', 'travType_Couples': '14', 'travType_Business': '9', 'travType_Families': '21', 'travType_Solo': '2'}, {'travType_Friends': '81', 'travType_Couples': '25', 'travType_Business': '13', 'travType_Families': '142', 'travType_Solo': '16'}, {'travType_Friends': '46', 'travType_Couples': '33', 'travType_Business': '9', 'travType_Families': '30', 'travType_Solo': '22'}, {'travType_Friends': '97', 'travType_Couples': '37', 'travType_Business': '19', 'travType_Families': '28', 'travType_Solo': '15'}, {'travType_Friends': '103', 'travType_Couples': '77', 'travType_Business': '30', 'travType_Families': '37', 'travType_Solo': '33'}, {'travType_Friends': '45', 'travType_Couples': '20', 'travType_Business': '6', 'travType_Families': '29', 'travType_Solo': '1'}, {'travType_Friends': '32', 'travType_Couples': '17', 'travType_Business': '32', 'travType_Families': '32', 'travType_Solo': '8'}, {'travType_Friends': 0, 'travType_Couples': '14', 'travType_Business': '28', 'travType_Families': '39', 'travType_Solo': '12'}, {'travType_Friends': '72', 'travType_Couples': '24', 'travType_Business': '61', 'travType_Families': '55', 'travType_Solo': '8'}, {'travType_Friends': '26', 'travType_Couples': '13', 'travType_Business': '18', 'travType_Families': '18', 'travType_Solo': '1'}, {'travType_Friends': '27', 'travType_Couples': '4', 'travType_Business': '3', 'travType_Families': '9', 'travType_Solo': '4'}, {'travType_Friends': '48', 'travType_Couples': '12', 'travType_Business': '3', 'travType_Families': '24', 'travType_Solo': '15'}, {'travType_Friends': '125', 'travType_Couples': '45', 'travType_Business': '13', 'travType_Families': '27', 'travType_Solo': '25'}, {'travType_Friends': '31', 'travType_Couples': '18', 'travType_Business': '36', 'travType_Families': '12', 'travType_Solo': '1'}, {'travType_Friends': '49', 'travType_Couples': '30', 'travType_Business': '46', 'travType_Families': '60', 'travType_Solo': '11'}, {'travType_Friends': '53', 'travType_Couples': '16', 'travType_Business': '16', 'travType_Families': '20', 'travType_Solo': '3'}, {'travType_Friends': '6', 'travType_Couples': '12', 'travType_Business': '7', 'travType_Families': '9', 'travType_Solo': '2'}, {'travType_Friends': 0, 'travType_Couples': '2', 'travType_Business': 0, 'travType_Families': '7', 'travType_Solo': '6'}, {'travType_Friends': '17', 'travType_Couples': '16', 'travType_Business': '8', 'travType_Families': '8', 'travType_Solo': '2'}, {'travType_Friends': '52', 'travType_Couples': '23', 'travType_Business': '12', 'travType_Families': '22', 'travType_Solo': '5'}, {'travType_Friends': '39', 'travType_Couples': '21', 'travType_Business': '5', 'travType_Families': '27', 'travType_Solo': '18'}, {'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Business': '113', 'travType_Families': '165', 'travType_Solo': '12'}, {'travType_Friends': '198', 'travType_Couples': '88', 'travType_Business': '81', 'travType_Families': '126', 'travType_Solo': '23'}, {'travType_Friends': '133', 'travType_Couples': '77', 'travType_Business': '61', 'travType_Families': '111', 'travType_Solo': '9'}, {'travType_Friends': '172', 'travType_Couples': '26', 'travType_Business': '22', 'travType_Families': '21', 'travType_Solo': '9'}, {'travType_Friends': '19', 'travType_Couples': '7', 'travType_Business': '18', 'travType_Families': '9', 'travType_Solo': '3'}, {'travType_Friends': '333', 'travType_Couples': '219', 'travType_Business': '32', 'travType_Families': '167', 'travType_Solo': '126'}, {'travType_Friends': '31', 'travType_Couples': '14', 'travType_Business': '9', 'travType_Families': '21', 'travType_Solo': '2'}, {'travType_Friends': '81', 'travType_Couples': '25', 'travType_Business': '13', 'travType_Families': '142', 'travType_Solo': '16'}, {'travType_Friends': '46', 'travType_Couples': '33', 'travType_Business': '9', 'travType_Families': '30', 'travType_Solo': '22'}, {'travType_Friends': '97', 'travType_Couples': '37', 'travType_Business': '19', 'travType_Families': '28', 'travType_Solo': '15'}, {'travType_Friends': '103', 'travType_Couples': '77', 'travType_Business': '30', 'travType_Families': '37', 'travType_Solo': '33'}, {'travType_Friends': '45', 'travType_Couples': '20', 'travType_Business': '6', 'travType_Families': '29', 'travType_Solo': '1'}, {'travType_Friends': '32', 'travType_Couples': '17', 'travType_Business': '32', 'travType_Families': '32', 'travType_Solo': '8'}, {'travType_Friends': 0, 'travType_Couples': '14', 'travType_Business': '28', 'travType_Families': '39', 'travType_Solo': '12'}, {'travType_Friends': '72', 'travType_Couples': '24', 'travType_Business': '61', 'travType_Families': '55', 'travType_Solo': '8'}, {'travType_Friends': '26', 'travType_Couples': '13', 'travType_Business': '18', 'travType_Families': '18', 'travType_Solo': '1'}, {'travType_Friends': '27', 'travType_Couples': '4', 'travType_Business': '3', 'travType_Families': '9', 'travType_Solo': '4'}, {'travType_Friends': '48', 'travType_Couples': '12', 'travType_Business': '3', 'travType_Families': '24', 'travType_Solo': '15'}, {'travType_Friends': '125', 'travType_Couples': '45', 'travType_Business': '13', 'travType_Families': '27', 'travType_Solo': '25'}, {'travType_Friends': '31', 'travType_Couples': '18', 'travType_Business': '36', 'travType_Families': '12', 'travType_Solo': '1'}, {'travType_Friends': '49', 'travType_Couples': '30', 'travType_Business': '46', 'travType_Families': '60', 'travType_Solo': '11'}, {'travType_Friends': '53', 'travType_Couples': '16', 'travType_Business': '16', 'travType_Families': '20', 'travType_Solo': '3'}, {'travType_Friends': '6', 'travType_Couples': '12', 'travType_Business': '7', 'travType_Families': '9', 'travType_Solo': '2'}, {'travType_Friends': 0, 'travType_Couples': '2', 'travType_Business': 0, 'travType_Families': '7', 'travType_Solo': '6'}, {'travType_Friends': '17', 'travType_Couples': '16', 'travType_Business': '8', 'travType_Families': '8', 'travType_Solo': '2'}, {'travType_Friends': '52', 'travType_Couples': '23', 'travType_Business': '12', 'travType_Families': '22', 'travType_Solo': '5'}, {'travType_Friends': '39', 'travType_Couples': '21', 'travType_Business': '5', 'travType_Families': '27', 'travType_Solo': '18'}, {'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Business': '113', 'travType_Families': '165', 'travType_Solo': '12'}, {'travType_Friends': '198', 'travType_Couples': '88', 'travType_Business': '81', 'travType_Families': '126', 'travType_Solo': '23'}, {'travType_Friends': '133', 'travType_Couples': '77', 'travType_Business': '61', 'travType_Families': '111', 'travType_Solo': '9'}, {'travType_Friends': '172', 'travType_Couples': '26', 'travType_Business': '22', 'travType_Families': '21', 'travType_Solo': '9'}, {'travType_Friends': '19', 'travType_Couples': '7', 'travType_Business': '18', 'travType_Families': '9', 'travType_Solo': '3'}, {'travType_Friends': '333', 'travType_Couples': '219', 'travType_Business': '32', 'travType_Families': '167', 'travType_Solo': '126'}, {'travType_Friends': '31', 'travType_Couples': '14', 'travType_Business': '9', 'travType_Families': '21', 'travType_Solo': '2'}, {'travType_Friends': '81', 'travType_Couples': '25', 'travType_Business': '13', 'travType_Families': '142', 'travType_Solo': '16'}, {'travType_Friends': '46', 'travType_Couples': '33', 'travType_Business': '9', 'travType_Families': '30', 'travType_Solo': '22'}, {'travType_Friends': '97', 'travType_Couples': '37', 'travType_Business': '19', 'travType_Families': '28', 'travType_Solo': '15'}, {'travType_Friends': '103', 'travType_Couples': '77', 'travType_Business': '30', 'travType_Families': '37', 'travType_Solo': '33'}, {'travType_Friends': '45', 'travType_Couples': '20', 'travType_Business': '6', 'travType_Families': '29', 'travType_Solo': '1'}, {'travType_Friends': '32', 'travType_Couples': '17', 'travType_Business': '32', 'travType_Families': '32', 'travType_Solo': '8'}, {'travType_Friends': 0, 'travType_Couples': '14', 'travType_Business': '28', 'travType_Families': '39', 'travType_Solo': '12'}, {'travType_Friends': '72', 'travType_Couples': '24', 'travType_Business': '61', 'travType_Families': '55', 'travType_Solo': '8'}, {'travType_Friends': '26', 'travType_Couples': '13', 'travType_Business': '18', 'travType_Families': '18', 'travType_Solo': '1'}, {'travType_Friends': '27', 'travType_Couples': '4', 'travType_Business': '3', 'travType_Families': '9', 'travType_Solo': '4'}, {'travType_Friends': '48', 'travType_Couples': '12', 'travType_Business': '3', 'travType_Families': '24', 'travType_Solo': '15'}, {'travType_Friends': '125', 'travType_Couples': '45', 'travType_Business': '13', 'travType_Families': '27', 'travType_Solo': '25'}, {'travType_Friends': '31', 'travType_Couples': '18', 'travType_Business': '36', 'travType_Families': '12', 'travType_Solo': '1'}, {'travType_Friends': '49', 'travType_Couples': '30', 'travType_Business': '46', 'travType_Families': '60', 'travType_Solo': '11'}, {'travType_Friends': '53', 'travType_Couples': '16', 'travType_Business': '16', 'travType_Families': '20', 'travType_Solo': '3'}, {'travType_Friends': '6', 'travType_Couples': '12', 'travType_Business': '7', 'travType_Families': '9', 'travType_Solo': '2'}, {'travType_Friends': 0, 'travType_Couples': '2', 'travType_Business': 0, 'travType_Families': '7', 'travType_Solo': '6'}, {'travType_Friends': '17', 'travType_Couples': '16', 'travType_Business': '8', 'travType_Families': '8', 'travType_Solo': '2'}, {'travType_Friends': '52', 'travType_Couples': '23', 'travType_Business': '12', 'travType_Families': '22', 'travType_Solo': '5'}, {'travType_Friends': '39', 'travType_Couples': '21', 'travType_Business': '5', 'travType_Families': '27', 'travType_Solo': '18'}, {'travType_Friends': '69', 'travType_Couples': '58', 'travType_Business': '8', 'travType_Families': '24', 'travType_Solo': '56'}, {'travType_Friends': '133', 'travType_Couples': '24', 'travType_Business': '8', 'travType_Families': '56', 'travType_Solo': '18'}, {'travType_Friends': '144', 'travType_Couples': '74', 'travType_Business': '31', 'travType_Families': '150', 'travType_Solo': '49'}, {'travType_Friends': '166', 'travType_Couples': '79', 'travType_Busi

In [45]:
vector = trav_typedf.T.to_dict().values()
#vector = trav_typedf.T.to_dict()
#print(vector)
X = vector.fit_transform(resulting_df2).toarray()
name_of_c = vector.get_feature_names()
print(X, name_of_c)

AttributeError: 'dict_values' object has no attribute 'fit_transform'

In [34]:
import numpy as np
from sklearn.cluster import KMeans

### For the purposes of this example, we store feature data from our
### dataframe `df`, in the `f1` and `f2` arrays. We combine this into
### a feature matrix `X` before entering it into the algorithm.
a = resulting_df2[['latitude','longitude']].values
b = resulting_df2[['travType_Business','travType_Couples','travType_Families','travType_Friends','travType_Solo']].values

X=np.matrix(zip(a,b))
kmeans = KMeans(n_clusters=2).fit(a)

In [35]:
kmeans

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [36]:
a

array([['31.952438', '35.937958'],
       ['31.963032', '35.89816'],
       ['31.951878', '35.9332'],
       ...,
       ['31.973347', '35.90616'],
       ['31.973473', '35.89811'],
       ['31.952627', '35.93221']], dtype=object)

In [ ]:
matrix = np.zeros((len(trav_typedf),len(trav_typedf))) 
i = 0
for x in trav_typedf:
    j = 0
    for y in trav_typedf:
        setA = set(x)
        setB = set(y)
            
        jacc_dist = (1 - (float(len(setA.intersection(setB))) / len(setA.union(setB)))) #compute jaccard distance
        matrix[i][j] = jacc_dist
        j += 1
        i += 1
print(matrix)

In [39]:
def plottingCluster(points, labels, gm=False, gm_name='cluster.html'):
    Labels = list(set(labels))
    colors = list(matplotlib.colors.cnames)[::2]
    X = dict()
    for b in range(len(labels)):
        if labels[b] in X:
            X[labels[b]][0].append(points[b][0])
            X[labels[b]][1].append(points[b][1])
        else:
            X[labels[b]] = [[], []]
            X[labels[b]][0].append(points[b][0])
            X[labels[b]][1].append(points[b][1])
    plt.figure(figsize=(20, 10))
    if gm:
        gmap = gmplot.GoogleMapPlotter(points[0][0], points[0][1], 11)
        for j in X:
            gmap.scatter(X[j][0], X[j][1], colors[Labels.index(j)], marker=True)
        gmap.draw(gm_name)
    for l in X:
        plt.scatter(X[l][0], X[l][1], color=colors[Labels.index(l)], label=str(l), marker=".")
    plt.legend()

print('k means ++')
districts(locations, X, name_of_c, 5, 2, 5, 'k-means++', 'cosine', 'k-means-clustering.html')

k means ++

NameError: name 'districts' is not defined